// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendees.sql

package database

import (
	"context"
	"database/sql"
)

const addAttendee = `-- name: AddAttendee :exec
INSERT INTO 
attendees (event_id, user_id) 
VALUES (?, ?)
`

type AddAttendeeParams struct {
	EventID sql.NullInt64
	UserID  sql.NullInt64
}

func (q *Queries) AddAttendee(ctx context.Context, arg AddAttendeeParams) error {
	_, err := q.db.ExecContext(ctx, addAttendee, arg.EventID, arg.UserID)
	return err
}

const getAllAttendeesForEvent = `-- name: GetAllAttendeesForEvent :many
SELECT id, user_id, event_id FROM attendees
WHERE event_id = (?)
`

func (q *Queries) GetAllAttendeesForEvent(ctx context.Context, eventID sql.NullInt64) ([]Attendee, error) {
	rows, err := q.db.QueryContext(ctx, getAllAttendeesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendee
	for rows.Next() {
		var i Attendee
		if err := rows.Scan(&i.ID, &i.UserID, &i.EventID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
