// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO 
events(owner_id, name, description, date, location) 
VALUES (?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	OwnerID     sql.NullInt64 `json:"owner_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Date        string        `json:"date"`
	Location    string        `json:"location"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Date,
		arg.Location,
	)
	return err
}

const deleteEventById = `-- name: DeleteEventById :exec
DELETE FROM events 
WHERE id = (?)
`

func (q *Queries) DeleteEventById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventById, id)
	return err
}

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, owner_id, name, description, date, location FROM events
`

func (q *Queries) GetAllEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Date,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByName = `-- name: GetEventByName :many
SELECT id, owner_id, name, description, date, location FROM events 
WHERE name = (?)
`

func (q *Queries) GetEventByName(ctx context.Context, name string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Date,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByOwner = `-- name: GetEventByOwner :many
SELECT id, owner_id, name, description, date, location FROM events 
WHERE owner_id = (?)
`

func (q *Queries) GetEventByOwner(ctx context.Context, ownerID sql.NullInt64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Date,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events 
SET 
    description = COALESCE(NULLIF(?, ''), description),
    date = COALESCE(NULLIF(?, ''), date),
    location = COALESCE(NULLIF(?, ''), location)
WHERE id = (?)
`

type UpdateEventParams struct {
	NULLIF   interface{} `json:"NULLIF"`
	NULLIF_2 interface{} `json:"NULLIF_2"`
	NULLIF_3 interface{} `json:"NULLIF_3"`
	ID       int64       `json:"id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.ExecContext(ctx, updateEvent,
		arg.NULLIF,
		arg.NULLIF_2,
		arg.NULLIF_3,
		arg.ID,
	)
	return err
}
