// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO 
events(owner_id, name, description, date, location) 
VALUES (?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	OwnerID     sql.NullInt64
	Name        string
	Description string
	Date        string
	Location    string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Date,
		arg.Location,
	)
	return err
}

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, owner_id, name, description, date, location FROM events
`

func (q *Queries) GetAllEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Date,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByName = `-- name: GetEventByName :many
SELECT id, owner_id, name, description, date, location FROM events 
WHERE name = (?)
`

func (q *Queries) GetEventByName(ctx context.Context, name string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Date,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByOwner = `-- name: GetEventByOwner :many
SELECT id, owner_id, name, description, date, location FROM events 
WHERE owner_id = (?)
`

func (q *Queries) GetEventByOwner(ctx context.Context, ownerID sql.NullInt64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Date,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
