// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Attendee struct {
	ID      int64         `json:"id"`
	UserID  sql.NullInt64 `json:"user_id"`
	EventID sql.NullInt64 `json:"event_id"`
}

type Event struct {
	ID          int64         `json:"id"`
	OwnerID     sql.NullInt64 `json:"owner_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Date        string        `json:"date"`
	Location    string        `json:"location"`
}

type User struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password,omitempty"`
}
