// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Attendee struct {
	ID      int64
	UserID  sql.NullInt64
	EventID sql.NullInt64
}

type Event struct {
	ID          int64
	OwnerID     sql.NullInt64
	Name        string
	Description string
	Date        string
	Location    string
}

type User struct {
	ID       int64
	Name     string
	Email    string
	Password string
}
